In [1]:
import tensorflow as tf
import numpy as np

In [5]:
tensor_abs = tf.constant([-2.5, 6])
print(tf.abs(tensor_abs))

tf.Tensor([2.5 6. ], shape=(2,), dtype=float32)


In [6]:
tensor_complex = tf.constant([-2.25 + 4j])
print(tf.abs(tensor_complex))

tf.Tensor([4.58938994], shape=(1,), dtype=float64)


In [23]:
x = tf.constant([4.0])
print(tf.sqrt(4.0))

tf.Tensor(2.0, shape=(), dtype=float32)


In [27]:
tensor_sqrt = tf.constant([4, 9, 16, 25], dtype=tf.float32)
print(tensor_sqrt)
print(tf.sqrt(tensor_sqrt))

tf.Tensor([ 4.  9. 16. 25.], shape=(4,), dtype=float32)
tf.Tensor([2. 3. 4. 5.], shape=(4,), dtype=float32)


### mathematical operation (addition, substruction, multiplication, division)

In [29]:
x = tf.constant([1, 2, 3, 4, 5], dtype=tf.int32)
y = tf.constant([6, 7, 8, 9, 10], dtype=tf.int32)

In [31]:
print('Addition: ', tf.add(x, y))
print('Substruction: ', tf.subtract(x, y))
print('Multiplication: ', tf.multiply(x, y))
print('Division: ', tf.divide(x, y))

Addition:  tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
Substruction:  tf.Tensor([-5 -5 -5 -5 -5], shape=(5,), dtype=int32)
Multiplication:  tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)
Division:  tf.Tensor([0.16666667 0.28571429 0.375      0.44444444 0.5       ], shape=(5,), dtype=float64)


In [34]:
x = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y = tf.constant([6, 7, 0, 9, 10], dtype=tf.float32)

print('Division Inf: ', tf.divide(x, y))
print('Division no Inf: ', tf.math.divide_no_nan(x, y))

Division Inf:  tf.Tensor([0.16666667 0.2857143         inf 0.44444445 0.5       ], shape=(5,), dtype=float32)
Division no Inf:  tf.Tensor([0.16666667 0.2857143  0.         0.44444445 0.5       ], shape=(5,), dtype=float32)


#### Broadcast

In [35]:
x = tf.constant([1, 2, 3, 4, 5], dtype=tf.int32)
y = tf.constant([[6], [7]], dtype=tf.int32)

print('Addition: ', tf.add(x, y))

Addition:  tf.Tensor(
[[ 7  8  9 10 11]
 [ 8  9 10 11 12]], shape=(2, 5), dtype=int32)
