In [1]:
import tensorflow as tf 
import numpy as np

## Linear Algebra

#### Matrix Multiplication

In [3]:
x1 = tf.constant(
    [
        [1, 2, 3],
        [3, 4, 2]
    ]
)
x2 = tf.constant(
    [
        [10, 20, 30],
        [3, 4, 2],
        [6, 12, 32]
    ]
)

matrixMulti = tf.linalg.matmul(
    x1,
    x2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

print(matrixMulti)

tf.Tensor(
[[ 34  64 130]
 [ 54 100 162]], shape=(2, 3), dtype=int32)


In [4]:
print(x1@x2)

tf.Tensor(
[[ 34  64 130]
 [ 54 100 162]], shape=(2, 3), dtype=int32)


In [6]:
transpose = tf.transpose(x1)
print(transpose)

tf.Tensor(
[[1 3]
 [2 4]
 [3 2]], shape=(3, 2), dtype=int32)


In [4]:
x1 = tf.constant(
    [
        [
            [1, 2],
            [4, 3]
        ],
        [
            [12, 4],
            [2, 76]
        ],
        [
            [2, 1],
            [3, 78]
        ]
    ],
    dtype=tf.float32
)

x2 = tf.constant(
    [
        [
            [1, 2, 2],
            [12, 43, 22]
        ],
        [
            [22, 19, 3],
            [2, 11, 45]
        ],
        [
            [2, 1, 12],
            [3, 33, 82]
        ]
    ],
    dtype=tf.float32
)

print(x1)
print(x2)

tf.Tensor(
[[[ 1.  2.]
  [ 4.  3.]]

 [[12.  4.]
  [ 2. 76.]]

 [[ 2.  1.]
  [ 3. 78.]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[ 1.  2.  2.]
  [12. 43. 22.]]

 [[22. 19.  3.]
  [ 2. 11. 45.]]

 [[ 2.  1. 12.]
  [ 3. 33. 82.]]], shape=(3, 2, 3), dtype=float32)


In [5]:
tensor_multiplication = tf.linalg.matmul(x1, x2)
print(tensor_multiplication)

tf.Tensor(
[[[  25.   88.   46.]
  [  40.  137.   74.]]

 [[ 272.  272.  216.]
  [ 196.  874. 3426.]]

 [[   7.   35.  106.]
  [ 240. 2577. 6432.]]], shape=(3, 2, 3), dtype=float32)


In [3]:
tensor_band = tf.constant(
    [
        [0,  1,  2, 3],
        [-1,  0,  1, 2],
        [-2, -1,  0, 1],
        [-3, -2, -1, 0]
    ]
)
print(tensor_band)

tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)


In [5]:
upper = tf.linalg.band_part(tensor_band, 0, -1)  # Upper triangular part.
lower = tf.linalg.band_part(tensor_band, -1, 0)  # Lower triangular part.
diagonal = tf.linalg.band_part(tensor_band, 0, 0)  # Diagonal.

In [8]:
print('Upper: ', upper)
print('Lower: ', lower)
print('Diagonal: ', diagonal)

Upper:  tf.Tensor(
[[0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
Lower:  tf.Tensor(
[[ 0  0  0  0]
 [-1  0  0  0]
 [-2 -1  0  0]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
Diagonal:  tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [12]:
tensor_inv = tf.constant(
    [
        [2, 1, 6],
        [20, 12, 8],
        [22, 13, 40]
    ],
    dtype=tf.float32
)

inverse = tf.linalg.inv(tensor_inv)
print(inverse)

tf.Tensor(
[[ 3.6153831   0.36538446 -0.6153844 ]
 [-5.9999976  -0.49999973  0.9999995 ]
 [-0.03846148 -0.03846153  0.03846153]], shape=(3, 3), dtype=float32)


In [7]:
svd_matrix_A = tf.constant(
    [
        [2, 3],
        [4, 5],
        [6, 7]
    ],
    dtype=tf.float32
)
print(f'Matrix A: \n{svd_matrix_A}\n')

Matrix A: 
[[2. 3.]
 [4. 5.]
 [6. 7.]]



In [6]:
# Using tf.linalg.svd to calculate the singular value decomposition where d: Matrix D, u: Matrix U and v: Matrix V

d, u, v = tf.linalg.svd(svd_matrix_A, full_matrices=True, compute_uv=True)
print(f'Diagonal D: \n{d} \n\nMatrix U: \n{u} \n\nMatrix V^T: \n{v}')

Diagonal D: 
[11.782492    0.41578525] 

Matrix U: 
[[ 0.30449855 -0.86058956  0.40824753]
 [ 0.54340035 -0.19506174 -0.81649673]
 [ 0.78230214  0.47046405  0.40824872]] 

Matrix V^T: 
[[ 0.63453555  0.7728936 ]
 [ 0.7728936  -0.63453555]]
