In [2]:
import tensorflow as tf 

## Common TensorFlow Function

In [8]:
x = tf.constant([1, 2, 3 ,4])
x_expand= tf.expand_dims(x, axis=0) # axis can be a number based on the dimension of x

print(x.shape)
print(x_expand)
print(x_expand.shape)


(4,)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
(1, 4)


In [9]:
x_squeeze =tf.squeeze(x_expand, axis=0)
print(x_squeeze) 
print(x_squeeze.shape) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)


In [12]:
tensor_reshape = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_tensor = tf.reshape(tensor_reshape, [2, 2, 2])
print(reshaped_tensor)
print(tensor_reshape.shape)
print(reshaped_tensor.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(8,)
(2, 2, 2)


In [14]:
t1 = tf.constant(
    [
        [1, 2, 3],
        [10, 20, 30]
    ]
)
t2 = tf.constant(
    [
        [3, 4, 5],
        [30, 20, 50]
    ]
)

concatenate_rows = tf.concat([t1, t2], axis=0) # axis = 0 means across rows
concatenate_cols = tf.concat([t1, t2], axis=1) # axis = 0 means across cols

print(concatenate_rows)
print(concatenate_cols)

tf.Tensor(
[[ 1  2  3]
 [10 20 30]
 [ 3  4  5]
 [30 20 50]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  3  4  5]
 [10 20 30 30 20 50]], shape=(2, 6), dtype=int32)


In [15]:
# practice and see documentation for stack

In [18]:
t = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
paddings = tf.constant(
    [
        [1, 1,],
        [2, 2]
    ]
)

padding_constant = tf.pad(t, paddings, "CONSTANT")
padding_reflect = tf.pad(t, paddings, "REFLECT")
padding_symmetric = tf.pad(t, paddings, "SYMMETRIC")

print(f'Padding Constant\n{padding_constant}\n')
print(f'Padding Reflect\n{padding_reflect}\n')
print(f'Padding Symmetric\n{padding_symmetric}\n')

Padding Constant
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]

Padding Reflect
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]]

Padding Symmetric
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]]



In [14]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:4]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [13]:
tf.gather(params, [1, 2, 3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [15]:
tf.gather(params, tf.range(1, 4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>