In [1]:
import tensorflow as tf 

## Common TensorFlow Function

In [8]:
x = tf.constant([1, 2, 3 ,4])
x_expand= tf.expand_dims(x, axis=0) # axis can be a number based on the dimension of x

print(x.shape)
print(x_expand)
print(x_expand.shape)


(4,)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
(1, 4)


In [9]:
x_squeeze =tf.squeeze(x_expand, axis=0)
print(x_squeeze) 
print(x_squeeze.shape) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)


In [12]:
tensor_reshape = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_tensor = tf.reshape(tensor_reshape, [2, 2, 2])
print(reshaped_tensor)
print(tensor_reshape.shape)
print(reshaped_tensor.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(8,)
(2, 2, 2)


In [13]:
t1 = tf.constant(
    [
        [1, 2, 3],
        [10, 20, 30]
    ]
)
t2 = tf.constant(
    [
        [3, 4, 5],
        [30, 20, 50]
    ]
)

concatenate = tf.concat([t1, t2], axis=0) # axis = 0 means across rows
print(concatenate)

tf.Tensor(
[[ 1  2  3]
 [10 20 30]
 [ 3  4  5]
 [30 20 50]], shape=(4, 3), dtype=int32)
