In [2]:
import tensorflow as tf 

## Common TensorFlow Function

In [8]:
x = tf.constant([1, 2, 3 ,4])
x_expand= tf.expand_dims(x, axis=0) # axis can be a number based on the dimension of x

print(x.shape)
print(x_expand)
print(x_expand.shape)


(4,)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
(1, 4)


In [9]:
x_squeeze =tf.squeeze(x_expand, axis=0)
print(x_squeeze) 
print(x_squeeze.shape) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)


In [12]:
tensor_reshape = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_tensor = tf.reshape(tensor_reshape, [2, 2, 2])
print(reshaped_tensor)
print(tensor_reshape.shape)
print(reshaped_tensor.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(8,)
(2, 2, 2)


In [14]:
t1 = tf.constant(
    [
        [1, 2, 3],
        [10, 20, 30]
    ]
)
t2 = tf.constant(
    [
        [3, 4, 5],
        [30, 20, 50]
    ]
)

concatenate_rows = tf.concat([t1, t2], axis=0) # axis = 0 means across rows
concatenate_cols = tf.concat([t1, t2], axis=1) # axis = 0 means across cols

print(concatenate_rows)
print(concatenate_cols)

tf.Tensor(
[[ 1  2  3]
 [10 20 30]
 [ 3  4  5]
 [30 20 50]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  3  4  5]
 [10 20 30 30 20 50]], shape=(2, 6), dtype=int32)


In [15]:
# practice and see documentation for stack

In [18]:
t = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
paddings = tf.constant(
    [
        [1, 1,],
        [2, 2]
    ]
)

padding_constant = tf.pad(t, paddings, "CONSTANT")
padding_reflect = tf.pad(t, paddings, "REFLECT")
padding_symmetric = tf.pad(t, paddings, "SYMMETRIC")

print(f'Padding Constant\n{padding_constant}\n')
print(f'Padding Reflect\n{padding_reflect}\n')
print(f'Padding Symmetric\n{padding_symmetric}\n')

Padding Constant
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]

Padding Reflect
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]]

Padding Symmetric
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]]



In [14]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:4]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [13]:
tf.gather(params, [1, 2, 3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [15]:
tf.gather(params, tf.range(1, 4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [16]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])

In [17]:
tf.gather(params, indices=[3,1]).numpy()

array([[30., 31., 32.],
       [10., 11., 12.]], dtype=float32)

In [18]:
tf.gather(params, indices=[2,1], axis=1).numpy()

array([[ 2.,  1.],
       [12., 11.],
       [22., 21.],
       [32., 31.]], dtype=float32)

In [19]:
indices = [
    [0, 0],
    [1, 1]
]


params = tf.constant(
    [
        ['a', 'b'],
        ['c', 'd']
    ]
)

In [20]:
tf.gather_nd(indices=indices, params=params)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a', b'd'], dtype=object)>

In [24]:
tensor_two_d = [
    [1, 2, 3, 4],
    [1, 2],
    [1, 2, 3]
]


ragged_tensor = tf.ragged.constant(tensor_two_d)
print(ragged_tensor)
print(ragged_tensor.shape)

<tf.RaggedTensor [[1, 2, 3, 4], [1, 2], [1, 2, 3]]>
(3, None)


In [38]:
sparseTensor = tf.SparseTensor(
    indices=[[0, 0], [1, 2]],
    values=[1, 2],
    dense_shape=[3, 4]
)

In [39]:
print(sparseTensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
