In [1]:
import tensorflow as tf
import numpy as np

## Tensors

In [2]:
tensor_zero_d = tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1, 2, 3, 4, 5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
two_d = [
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400]
]
tensor_two_d = tf.constant(two_d)
print(tensor_two_d)

tf.Tensor(
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]], shape=(3, 4), dtype=int32)


In [7]:
three_d = [
    [
        [1, 2, 3, 4],
        [10, 20, 30, 40],
        [100, 200, 300, 400]
    ],
    [
        [5, 6, 7, 8],
        [50, 60, 70, 80],
        [500, 600, 700, 800.]
    ]
]
tensor_three_d = tf.constant(three_d)
print(tensor_three_d)

tf.Tensor(
[[[  1.   2.   3.   4.]
  [ 10.  20.  30.  40.]
  [100. 200. 300. 400.]]

 [[  5.   6.   7.   8.]
  [ 50.  60.  70.  80.]
  [500. 600. 700. 800.]]], shape=(2, 3, 4), dtype=float32)


In [8]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(3, 4)
(2, 3, 4)


In [13]:
four_d = [
    [
        [
            [1, 2, 3, 4],
            [10, 20, 30, 40],
            [100, 200, 300, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 70, 80],
            [500, 600, 700, 800]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
]

tensor_four_d = tf.constant(four_d, dtype=tf.float32)
print(tensor_four_d)

tf.Tensor(
[[[[  1.   2.   3.   4.]
   [ 10.  20.  30.  40.]
   [100. 200. 300. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.  70.  80.]
   [500. 600. 700. 800.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]], shape=(3, 2, 3, 4), dtype=float32)


In [2]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [7]:
tensor_one_d = tf.constant([1, 2, 0, 4, 5], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([1. 2. 0. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([ True  True False  True  True], shape=(5,), dtype=bool)


In [8]:
tensor_string = tf.constant(['Hello', 'World', 'Hi'])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'Hi'], shape=(3,), dtype=string)


In [10]:
np_array = np.array([1, 2, 3, 4])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [13]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [16]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [18]:
fill_tensor = tf.fill(
    [2, 3, 4],
    5,
    name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [19]:
ones_tensor = tf.ones(
    [3, 4],
    5,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int16)


In [21]:
once_like_tensor = tf.ones_like(
    fill_tensor
)
print(once_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [2]:
zeros_tensor = tf.zeros(
    [3, 4],
    5,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int16)


In [4]:
print(zeros_tensor.shape)
print(tf.shape(zeros_tensor))

(3, 4)
tf.Tensor([3 4], shape=(2,), dtype=int32)


In [6]:
print(tf.rank(zeros_tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [10]:
print(tf.size(zeros_tensor))

tf.Tensor(12, shape=(), dtype=int32)


In [13]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-0.7962574   0.7524851 ]
 [ 0.33656102 -0.46227238]
 [ 0.3523811   0.9900401 ]], shape=(3, 2), dtype=float32)


In [15]:
random_tensor_normal = tf.random.normal(
    [3, 2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor_normal)

tf.Tensor(
[[ 99.81335 100.07506]
 [100.78943  98.89623]
 [ 99.3827   99.69994]], shape=(3, 2), dtype=float32)


In [16]:
random_tensor_uniform = tf.random.uniform(
    [3, 2],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor_uniform)

tf.Tensor(
[[0.5521672  0.22616291]
 [0.50519717 0.07761967]
 [0.94408166 0.39000118]], shape=(3, 2), dtype=float32)


In [19]:
random_tensor_uniform = tf.random.uniform(
    [5, 5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor_uniform)

tf.Tensor(
[[53 59 86 22 12]
 [11 25 18 35 47]
 [17 99  1 71 63]
 [65 14 93 92 98]
 [40 17  7 27  1]], shape=(5, 5), dtype=int32)


In [5]:
tensor_index = tf.constant([1, 2, 3, 44, 55, 67])
print(tensor_index)
print(tensor_index[:4])
print(tensor_index[4:])
print(tensor_index[2:6])
print(tensor_index[1:-2])
print(tensor_index[1:8:2])

tf.Tensor([ 1  2  3 44 55 67], shape=(6,), dtype=int32)
tf.Tensor([ 1  2  3 44], shape=(4,), dtype=int32)
tf.Tensor([55 67], shape=(2,), dtype=int32)
tf.Tensor([ 3 44 55 67], shape=(4,), dtype=int32)
tf.Tensor([ 2  3 44], shape=(3,), dtype=int32)
tf.Tensor([ 2 44 67], shape=(3,), dtype=int32)


In [12]:
random_tensor_uniform = tf.random.uniform(
    [5, 5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print('Tensor: ', random_tensor_uniform)
print('Slicing: ', random_tensor_uniform[1:3, 3:])
print('Indexing row: ', random_tensor_uniform[1,:])
print('Indexing col: ', random_tensor_uniform[:, 1])
print('Spread: ', random_tensor_uniform[..., 1])

Tensor:  tf.Tensor(
[[29 64 40 24 70]
 [46 77 81 36 95]
 [21 76 47 16 20]
 [10 49 57 84  2]
 [73  6 30  6 14]], shape=(5, 5), dtype=int32)
Slicing:  tf.Tensor(
[[36 95]
 [16 20]], shape=(2, 2), dtype=int32)
Indexing row:  tf.Tensor([46 77 81 36 95], shape=(5,), dtype=int32)
Indexing col:  tf.Tensor([64 77 76 49  6], shape=(5,), dtype=int32)
Spread:  tf.Tensor([64 77 76 49  6], shape=(5,), dtype=int32)
