In [1]:
import tensorflow as tf

## Tensors

In [2]:
tensor_zero_d = tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1, 2, 3, 4, 5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
two_d = [
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400]
]
tensor_two_d = tf.constant(two_d)
print(tensor_two_d)

tf.Tensor(
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]], shape=(3, 4), dtype=int32)


In [7]:
three_d = [
    [
        [1, 2, 3, 4],
        [10, 20, 30, 40],
        [100, 200, 300, 400]
    ],
    [
        [5, 6, 7, 8],
        [50, 60, 70, 80],
        [500, 600, 700, 800.]
    ]
]
tensor_three_d = tf.constant(three_d)
print(tensor_three_d)

tf.Tensor(
[[[  1.   2.   3.   4.]
  [ 10.  20.  30.  40.]
  [100. 200. 300. 400.]]

 [[  5.   6.   7.   8.]
  [ 50.  60.  70.  80.]
  [500. 600. 700. 800.]]], shape=(2, 3, 4), dtype=float32)


In [8]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(3, 4)
(2, 3, 4)


In [13]:
four_d = [
    [
        [
            [1, 2, 3, 4],
            [10, 20, 30, 40],
            [100, 200, 300, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 70, 80],
            [500, 600, 700, 800]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
]

tensor_four_d = tf.constant(four_d, dtype=tf.float32)
print(tensor_four_d)

tf.Tensor(
[[[[  1.   2.   3.   4.]
   [ 10.  20.  30.  40.]
   [100. 200. 300. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.  70.  80.]
   [500. 600. 700. 800.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]], shape=(3, 2, 3, 4), dtype=float32)
