In [9]:
import tensorflow as tf
import numpy as np

## Tensors

In [2]:
tensor_zero_d = tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1, 2, 3, 4, 5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
two_d = [
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400]
]
tensor_two_d = tf.constant(two_d)
print(tensor_two_d)

tf.Tensor(
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]], shape=(3, 4), dtype=int32)


In [7]:
three_d = [
    [
        [1, 2, 3, 4],
        [10, 20, 30, 40],
        [100, 200, 300, 400]
    ],
    [
        [5, 6, 7, 8],
        [50, 60, 70, 80],
        [500, 600, 700, 800.]
    ]
]
tensor_three_d = tf.constant(three_d)
print(tensor_three_d)

tf.Tensor(
[[[  1.   2.   3.   4.]
  [ 10.  20.  30.  40.]
  [100. 200. 300. 400.]]

 [[  5.   6.   7.   8.]
  [ 50.  60.  70.  80.]
  [500. 600. 700. 800.]]], shape=(2, 3, 4), dtype=float32)


In [8]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(3, 4)
(2, 3, 4)


In [13]:
four_d = [
    [
        [
            [1, 2, 3, 4],
            [10, 20, 30, 40],
            [100, 200, 300, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 70, 80],
            [500, 600, 700, 800]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
    [
        [
            [14, 3, 34, 45],
            [10, 20, 32, 43],
            [100, 22, 330, 400]
        ],
        [
            [5, 6, 7, 8],
            [50, 60, 3, 80],
            [500, 600, 730, 820]
        ]
    ],
]

tensor_four_d = tf.constant(four_d, dtype=tf.float32)
print(tensor_four_d)

tf.Tensor(
[[[[  1.   2.   3.   4.]
   [ 10.  20.  30.  40.]
   [100. 200. 300. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.  70.  80.]
   [500. 600. 700. 800.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]


 [[[ 14.   3.  34.  45.]
   [ 10.  20.  32.  43.]
   [100.  22. 330. 400.]]

  [[  5.   6.   7.   8.]
   [ 50.  60.   3.  80.]
   [500. 600. 730. 820.]]]], shape=(3, 2, 3, 4), dtype=float32)


In [2]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [7]:
tensor_one_d = tf.constant([1, 2, 0, 4, 5], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([1. 2. 0. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([ True  True False  True  True], shape=(5,), dtype=bool)


In [8]:
tensor_string = tf.constant(['Hello', 'World', 'Hi'])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'Hi'], shape=(3,), dtype=string)


In [10]:
np_array = np.array([1, 2, 3, 4])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [13]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [16]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)
